#!/bin/busybox sh

mount -t devtmpfs   none            /dev
mount -t proc       none            /proc
mount -t sysfs      none            /sys
mount -t devpts     none            /dev/pts

echo "----------------------------------------"
echo "XPENOLOGY Kernel for Barcelona"
echo "----------------------------------------"
echo "init script, PID:$$"
echo "----------------------------------------"

    
exec /bin/busybox sh





